server:
  port: 8080

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notifications
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: dev.snds_prfct.rs.common.kafka.*


kafka:
  consumers:
    topics:
      recommendations:
        topic: recommendation-system.recommendations


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics