apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:12.3.2
          name: grafana
          resources:
            requests:
              cpu: "1"
              memory: "100M"
            limits:
              cpu: "2"
              memory: "300M"
