apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    system: "true"

---

apiVersion: v1
kind: Namespace
metadata:
  name: metrics
  labels:
    system: "true"

---

apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    system: "true"
