apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
    group: microservices
    system: "true"
  name: notification-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: notification-service
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
    group: microservices
    system: "true"
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - image: snds_prfct/notification-service:0.1
          name: notification-service
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-broker.kafka.svc.cluster.local:9092
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "250m"
              memory: "200M"
            limits:
              cpu: "500m"
              memory: "500M"
