apiVersion: v1
kind: Service
metadata:
  labels:
    app: recommendation-service
  name: recommendation-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: recommendation-service
  type: ClusterIP
status:
  loadBalancer: {}
