server:
  port: 8080

spring:
  application:
    name: recommendation-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: recommendations
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: dev.snds_prfct.rs.common.kafka.*

kafka:
  consumer:
    topics:
      users-activity:
        topic: recommendation-system.user-activity
  producer:
    topics:
      recommendations:
        topic: recommendation-system.recommendations
        partitions: 3

scheduling:
  recommendations:
    blog-post:
      fixed-delay-millis: 20000
    friends:
      fixed-delay-millis: 20000
    premium-users-news:
      fixed-delay-millis: 50000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics